language: node_js
node_js:
	- "6"
cache:
	directories:
		- node_modules
		- uml-parser/node_modules
		- test-generator/node_modules
		- smt-generator/node_modules
install:
	- npm install
	- npm install -g grunt-cli
before_script:
	- grunt lint
script:
	- echo "1"
