sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g grunt-cli codecov
before_script:
  - grunt lint
script:
  - grunt coverage
after_script:
  - codecov -f coverage/coverage.json
