dist: trusty
sudo: false
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g grunt-cli codecov
  - wget -q https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip
  - unzip -q z3-4.5.0-x64-ubuntu-14.04.zip
  - export PATH=$PATH:$PWD/z3-4.5.0-x64-ubuntu-14.04/bin
before_script:
  - grunt lint
script:
  - grunt coverage
after_script:
  - grunt clean
  - codecov --disable=gcov -f coverage/coverage.json
