coverage:
  precision: 2
  range: 70..100
  round: up

  status:
    project:
      default:
        target: 70%
        threshold: null
        base: auto

  parsers:
    javascript:
      enable_partials: yes

comment:
  layout: "header, diff"
  behavior: "new"
  require_changes: false
